sudo: required
services:
  - docker

before_install:
  - docker build -t pkansal/react-test -f  ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pkansal/react-test npm test

after_success:
  - docker build -t pkansal/multi-client ./client
  - docker build -t pkansal/multi-nginx ./nginx
  - docker build -t pkansal/multi-server ./server
  - docker build -t pkansal/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push pkansal/multi-client
  - docker push pkansal/multi-nginx
  - docker push pkansal/multi-server
  - docker push pkansal/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-486785349756'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
